# Generated by Django 3.1.5 on 2021-01-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gameuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images')),
                ('sids', models.TextField(default='')),
            ],
        ),
    ]
