# Generated by Django 3.1.5 on 2021-01-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
