# Generated by Django 3.1.5 on 2021-02-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_card2user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='card2user',
            name='is_right',
            field=models.BooleanField(default=False),
        ),
    ]
