# Generated by Django 3.1.5 on 2021-02-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_card2user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card2user',
            name='position',
            field=models.CharField(choices=[('hand', 'hand'), ('table', 'table')], default='betor', max_length=10),
        ),
    ]
