# Generated by Django 3.1.5 on 2021-02-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_propose'),
    ]

    operations = [
        migrations.AddField(
            model_name='propose',
            name='is_right',
            field=models.BooleanField(default=False),
        ),
    ]
