# Generated by Django 3.1.5 on 2021-02-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_card2user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card2user',
            name='position',
            field=models.CharField(choices=[('hand', 'hand'), ('table', 'table')], default='hand', max_length=10),
        ),
    ]
