# Generated by Django 3.1.5 on 2021-02-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20210202_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='card2user',
            name='is_right',
            field=models.BooleanField(default=False),
        ),
    ]
