# Generated by Django 3.1.5 on 2021-02-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_propose'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='state',
            field=models.CharField(choices=[('gessor', 'gessor'), ('gessed', 'gessed'), ('betor', 'betor'), ('beted', 'beted'), ('proposer', 'proposer'), ('proposed', 'proposed')], default='betor', max_length=10),
        ),
    ]
