# Generated by Django 3.1.5 on 2021-02-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_gameuser_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='association',
            field=models.TextField(default='empty'),
        ),
    ]
