# Generated by Django 3.1.5 on 2021-02-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_card2user_is_down'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='account',
            field=models.IntegerField(default=0),
        ),
    ]
