# Generated by Django 3.1.5 on 2021-02-03 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_gameuser_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameuser',
            name='password',
        ),
    ]
